### ISSUE TITLE
真机调试手机显示白屏

### ISSUE THREAD

**Issue by 2286721642** [wszgrcy/angular-miniprogram-template#4]
<img width="593" alt="QQ20220708-163213@2x" src="https://user-images.githubusercontent.com/43333114/177952100-b04c25e6-a711-4d63-aea7-dd25a4e18c32.png">
<img width="787" alt="image" src="https://user-images.githubusercontent.com/43333114/177953090-26ee5c01-e748-40ad-8ab0-470d0fbbc5a4.png">

看了只有page标签，预览倒是正常

**Comment by 2286721642** [comment]
以上是npm run build:prod的结果。
如果是npm run build那么预览和真机调试都直接报错

<img width="391" alt="image" src="https://user-images.githubusercontent.com/43333114/177955110-5418ae3e-a99b-4ca7-b00b-bc0fe4012444.png">

**Comment by wszgrcy** [comment]
感谢反馈.请问是跑的demo还是?

**Comment by wszgrcy** [comment]
刚才试了下 首先dev模式真机调试不行(需要prod),第二个就是组件声明默认需要增加"component":true (模拟器上正常但是真机调试有问题)....这个我明天修改下....

**Comment by 2286721642** [comment]
dev下报错好像是上传代码检查不支持?.的语法，所以只能prod了。真机调试报错好像是PageService里this.app.__ngStartPage被赋予函数之前就被调用然后就报错了

**Comment by wszgrcy** [comment]
试了下[angular-miniprogram-realword](https://github.com/wszgrcy/angular-miniprogram-realworld)真机调试正常(1.0,2.0一些简单的逻辑,至少显示是正常的没有保存),如果你能复现的话可以提pr给这个项目,然后我试试什么情况下会导致这种问题

**Comment by 2286721642** [comment]
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/43333114/178099341-92afa67e-ec8e-4c30-8003-89fbba5311d2.png">
angular-miniprogram-realworld这个项目的真机调试还是这样，这是下载后没有改动直接跑的结果

**Comment by 2286721642** [comment]
我找安卓试了，安卓的真机调试能正常显示。ios不正常有报错

**Comment by wszgrcy** [comment]
> <img alt="image" width="1131" src="https://user-images.githubusercontent.com/43333114/178099341-92afa67e-ec8e-4c30-8003-89fbba5311d2.png">
> 
> angular-miniprogram-realworld这个项目的真机调试还是这样，这是下载后没有改动直接跑的结果
> 刚刚试了mac和windows下的微信开发者工具都这样
> 
> 我发现你的[angular-miniprogram](https://github.com/wszgrcy/angular-miniprogram) src/common/http下是空的，没法build啊

感谢反馈....不过手里没有ios机型.....我看看咋回事..代码应该一样的.可能是因为内核(v8和jscore)执行不同?
